name: CI/CD Node.js

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.FJRRMDHN }} >> ~/.ssh/known_hosts

      - name: Jalankan testing (optional)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.FJRRMDHN }}
          username: ${{ secrets.rafiqfjrrmdhn }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/rafiqfjrrmdhn/CRUD
            git pull origin master
            pm2 restart app
